version: "2.4"

services:
  base:
    image: gradle:7.4.1-jdk11
    working_dir: /app
    volumes:
      - .:/app

  app:
    extends:
      service: base
    ports:
      - "8080:8080"
      - "5005:5005"
    command: ./gradlew bootRun
    depends_on:
      - db

  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: spring_boot_demo
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./src/main/resources/db/schema/create_user.sql:/docker-entrypoint-initdb.d/init.sql"
