version: "2.4"

services:
  base:
    image: gradle:7.4.1-jdk11
    working_dir: /app
    volumes:
      - .:/app

  app:
    extends:
      service: base
    ports:
      - "8080:8080"
      - "5005:5005"
    command: ./gradlew bootRun
    depends_on:
      - mysql_base

  mysql_base:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
